name: Deploy to ECS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: bagisto-app
  ECS_SERVICE: bagisto-staging-service
  ECS_CLUSTER: bagisto-staging-cluster

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push single image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build single image for all services
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "Single image built: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Force ECS deployments for all services
      run: |
        echo "Forcing ECS service deployments..."
        
        # Update web service
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --force-new-deployment \
          --region $AWS_REGION
        
        # Update queue worker service
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service bagisto-staging-queue-worker \
          --force-new-deployment \
          --region $AWS_REGION || echo "Queue service will be created"
        
        # Update scheduler service
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service bagisto-staging-scheduler \
          --force-new-deployment \
          --region $AWS_REGION || echo "Scheduler service will be created"
        
        echo "All services updated with same image!"
