name: Destroy ECR Repository

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY-ECR" to confirm ECR repository deletion'
        required: true
        type: string

env:
  AWS_REGION: ap-southeast-2

jobs:
  validate:
    name: Validate Destroy Request
    runs-on: ubuntu-latest
    
    steps:
    - name: Validate Confirmation
      run: |
        if [ "${{ github.event.inputs.confirm_destroy }}" != "DESTROY-ECR" ]; then
          echo "❌ Confirmation failed. You must type 'DESTROY-ECR' to proceed."
          exit 1
        fi
        echo "✅ ECR destroy confirmation validated"

  destroy-ecr:
    name: Destroy ECR Repository
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Destroy
      run: |
        cd terraform
        terraform destroy -auto-approve

    - name: Cleanup Confirmation
      run: |
        echo "🗑️ ECR Repository destroyed!"
        echo "📊 Resources removed:"
        echo "  - ECR Repository: bagisto-app"
        echo "  - All Docker images deleted"
        echo "  - Lifecycle policies removed"
